### PR TITLE
Join

### PR DESCRIPTION
**Pull request by saisha-r**
This is the training page. It's titled "join" instead of "training" on the navigation bar so that there is more space and doesn't look too cluttered (let me know if you want me to change this!)

### CODE REVIEW

**Review by aaronjnewman — CHANGES_REQUESTED** [review]
- change title from "Training" to "Training: Do you want to join NCIL?"
- add a Navigation "bar" (it can just be a line of text with hyperlinks to the sections) that lists "Undergraduate | Graduate | Postdoctoral" - I just want it to be clear at the top of the page that it's not just for undergrads
- Prior to the Undergraduate Students heading, please add these paragraphs (which are also on the landing page, but bear repeating here):

> The NeuroCognitive Imaging lab is a group of enthusiastic researchers interested in cognitive neuroscience. Our team comprises individuals with diverse backgrounds, interests, and skill sets. This includes undergraduate and graduate students, postdoctoral scholars, and professional research assistants. If you are interested in joining the lab as a volunteer, student, or other trainee, please contact us!
> 
> NCIL is committed to providing a safe, diverse, inclusive, and equitable environment for learning and working. We welcome trainees from all backgrounds, both locally and internationally. In particular, we welcome and encourage participation by people from African Nova Scotian and Mi’kmaq communities. We recognize the barriers to participation in academia that these and other groups have experienced, and we actively work to support future scholars from historically marginalized communities.
> 

- Grad training title: change MSC to MSc and PHD to PhD
- 3rd para under grad training: add to the end of the last sentence (after Dal Innovates): "or the national invention2Innovation program." Link that to https://beedie.sfu.ca/programs/graduate/invention-to-innovation

**Comment by saisha-r** [comment]
@aaronjnewman I added the requested changes. In regard to changing MSC to MSc and PHD to PhD for the grad training title, the reason why it's capitalized is because of the markdown format for that heading style (when you use a heading with 1 #, every character is capitalized). So, with that style heading I can't make letters lowercase. I decided to remove MSc and PhD from the title since those degrees are mentioned early on in that section anyway, but let me know if you want me to put it back.

**Comment by aaronjnewman** [comment]
Looking great, @saisha-r - I like the navbar and agree about simplifiying the grad section title.

Under volunteers, I read more closely and realized it's outdated text. Can you please replace it with the following. Note I've added our email address rather than the "..." currently there. It would be great if you could build a webform (a la what you did for SKIRF?) if you haven't already  - maybe the ... was a placeholder? But nice to have an email address as the placeholder at any rate. Anyway, revised text is:

We generally ask all volunteers to make a **minimum 3 hour/week commitment** to the lab. We won’t necessarily have 3 hours of work each week for you, but at times when the lab is busy, we do. Volunteers typically help with data collection (EEG and behavioural), data entry, organizational tasks around data management, stimulus development, etc.. We find that 3 hours/week is a reasonable amount of time to actually learn something from your experience over the course of a term, and decide if you want to get more deeply involved in a project.

Rather than schedule volunteers at specific times/days of the week, we post all volunteer opportunities on our communication platform (Basecamp), and we expect you to sign up for those that you are available for. As well, **you should try to attend weekly lab meetings** so we get to know your face, and get familiar with the many projects going on in the lab. Times and locations for the meetings are posted on Basecamp, and we hold them hybrid with a Zoom option if you can’t make it to the LSC. 

If you would like to volunteer, please [email us](mailto:NCIL@dal.ca)

**Comment by saisha-r** [comment]
I updated the text for volunteers. I would be happy to create a web form, but in the meantime, I put the email as requested. 

To create the web form, I will need to make an account on FormSpree with the email you want the web form responses to be sent to. Would it be for NCIL@dal.ca? Whoever has access to the email will have to accept the confirmation email for creating the account. Also, what kind of questions would you want to be included in the web form?

**Comment by aaronjnewman** [comment]
Yes, please direct the webform to NCIL@dal.ca

In terms of quesitons, let's connect w Cindy on Basecamp as I have some ideas but she will too.

**Comment by aaronjnewman** [comment]
Looks like the CSS is still not working, so I assume this is a work in progress.

A few things though: 
- please create a button on the "join" page to link to the form, rather than just a link in the text. A clear "call to action" button is always a good idea.
- I don't know what Cindy had in mind with asking if people have taken PSYO 2093, because that's not even an actual class. Please change both to NESC/PSYO, and change 2093 to 3505
- please ask for their B00 number
- in the section at the bottom on TCPS, please amend the second sentence to read, "If you have not yet achieved this certification, you do not need to do it before you submit this form. We will follow up with information on completing it once we have reviewed your application." - and then cut the rest of it (information for later is not worth putting in a form they won't be able to acess later)
- Move the quesiton about LinkedIn up next to the CV. Because, we only need either CV or LinkedIn profile - so please put them together and clarify we only need one

**Review by aaronjnewman — APPROVED** [review]

**Pull request closed without merging**
