### PR TITLE
updated titles and content for project descriptions main page, and reordered items

### PR DESCRIPTION
**Pull request by aaronjnewman**
@saisha-r please read it over and make sure it's all comprehensible and grammatical etc :)

### CODE REVIEW

**Comment by aaronjnewman** [comment]
Thanks @saisha-r!

I notice now that the images are a bit slow to download - especailly on a slow connection. Can you please check that they are optimized for size and compression (JPEGs should be compressed at 70-90%) and/or do that? You can probably figure out how if you don't already know, but ask me or Danny if you need help. Thanks!

**Comment by saisha-r** [comment]
Photos have been compressed (didn't change the hyperscanning one you added since its file size and resolution were low, so I am assuming you already compressed this one). I also changed some of the photos. For BCI, I used an image Brynn sent me; for the rest of the photos I changed, I used stock photos. For the SKIRF project, I was wondering if a photo from our SKIRF videos would be better (nothing would show children reading though, just either an image of administrating the WIAT or something with the IWK MRI).

**Comment by aaronjnewman** [comment]
yes, I think for SKIRF maybe a photo of kid in MRI would be most representative

**Comment by saisha-r** [comment]
The production effect study's photo is cut off. I tried adjusting the aspect ratio of the photo but that looked weirder. Should we just crop it and put one of the brains for the photo instead of the two side-by-side?

**Comment by aaronjnewman** [comment]
photos are loading slowly or not at all...

**Comment by saisha-r** [comment]
Oh, I compressed them and they loaded fine for me. I just compressed them further now - let me know if it's still not loading!

**Review by saisha-r — APPROVED** [review]

**Pull request merged**
